AllCops:
  NewCops: enable

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false
